# Generated by Django 5.2.3 on 2025-06-24 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_about_alter_product_id_alter_product_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='creating_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
