# Generated by Django 5.2.3 on 2025-06-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_about_creating_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='creating_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
